### ISSUE TITLE
CI randomly failing with cache

### ISSUE THREAD

**Issue by outsideris** [bosnet/sebak#111]
* [Failed job](https://circleci.com/gh/bosnet/sebak/149)
* [Passed job without cache](https://circleci.com/gh/bosnet/sebak/154)

I don't know why.  However, it's annoying.

It can be CI's cache problem.

**Comment by outsideris** [comment]
It looks like timing issue, not cache.

**Comment by outsideris** [comment]
To find this problem, I also will add TravisCI as @spikeekips suggestion.

**Comment by outsideris** [comment]
We didn't find the cause and there is wasted time a lot.

If you encounter some random fail in CI, please paste the error message below as comments.

**Comment by kfangw** [comment]
https://circleci.com/gh/bosnet/sebak/491
```
=== RUN   TestNodeRunnerCreateAccount
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x7faaa5]

goroutine 21313 [running]:
boscoin.io/sebak/lib.VotingStateStaging.IsClosed(...)
	/go/src/boscoin.io/sebak/lib/voting.go:309
boscoin.io/sebak/lib.(*VotingResult).IsClosed(...)
	/go/src/boscoin.io/sebak/lib/voting.go:123
boscoin.io/sebak/lib.(*ISAAC).receiveBallotVotingStates(0xc4205ee640, 0xc429f702f8, 0x6, 0xc4204dcff0, 0x2c, 0xc420648780, 0x58, 0xc4204dd020, 0x2c, 0xc429f7a400, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:173 +0x1b5
boscoin.io/sebak/lib.(*ISAAC).ReceiveBallot(0xc4205ee640, 0xc429f702f8, 0x6, 0xc4204dcff0, 0x2c, 0xc420648780, 0x58, 0xc4204dd020, 0x2c, 0xc429f7a400, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:85 +0x145
boscoin.io/sebak/lib.CheckNodeRunnerHandleBallotReceiveBallot(0xbb4f00, 0xc4327d2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/boscoin.io/sebak/lib/node_runner_checker.go:167 +0xec
boscoin.io/sebak/lib/common.RunChecker(0xbb4f00, 0xc4327d2000, 0xc4203b4420, 0x0, 0x0, 0x0, 0xc4327fca00, 0x32)
	/go/src/boscoin.io/sebak/lib/common/checker.go:24 +0xe9
boscoin.io/sebak/lib.(*NodeRunner).handleMessage(0xc4200b0680)
	/go/src/boscoin.io/sebak/lib/node_runner.go:248 +0x4df
created by boscoin.io/sebak/lib.(*NodeRunner).Start
	/go/src/boscoin.io/sebak/lib/node_runner.go:76 +0x51
FAIL	boscoin.io/sebak/lib	18.811s
```

**Comment by Geod24** [comment]
```
=== RUN   TestNodeRunnerCreateAccount
--- FAIL: TestNodeRunnerCreateAccount (1.56s)
	node_runner_create_account_test.go:80: failed to get consensus
[...]
=== RUN   TestNodeRunnerCreateAccountSufficient
--- FAIL: TestNodeRunnerCreateAccountSufficient (1.56s)
	node_runner_create_account_test.go:268: failed to get consensus
[...]
=== RUN   TestNodeRunnerPayment
--- FAIL: TestNodeRunnerPayment (1.56s)
	node_runner_payment_test.go:86: failed to get consensus
=== RUN   TestNodeRunnerSerializedPayment
--- FAIL: TestNodeRunnerSerializedPayment (1.54s)
	node_runner_payment_test.go:199: failed to get 1st consensus
```

https://circleci.com/gh/bosnet/sebak/519

**Comment by kfangw** [comment]
```
=== RUN   TestNodeRunnerConsensusSameSourceWillNotIgnored
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x80e188]

goroutine 47562 [running]:
boscoin.io/sebak/lib.VotingStateStaging.IsClosed(...)
	/go/src/boscoin.io/sebak/lib/voting.go:311
boscoin.io/sebak/lib.(*VotingResult).IsClosed(...)
	/go/src/boscoin.io/sebak/lib/voting.go:125
boscoin.io/sebak/lib.(*ISAAC).receiveBallotVotingStates(0xc422eca2d0, 0xc42058a500, 0x6, 0xc422ec8a20, 0x2c, 0xc4268c21e0, 0x58, 0xc424b99540, 0x38, 0xc422ec8a50, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:178 +0x238
boscoin.io/sebak/lib.(*ISAAC).ReceiveBallot(0xc422eca2d0, 0xc42058a500, 0x6, 0xc422ec8a20, 0x2c, 0xc4268c21e0, 0x58, 0xc424b99540, 0x38, 0xc422ec8a50, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:85 +0x145
boscoin.io/sebak/lib.CheckNodeRunnerHandleBallotReceiveBallot(0xbe4fc0, 0xc42680a000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/boscoin.io/sebak/lib/node_runner_checker.go:163 +0xec
boscoin.io/sebak/lib/common.RunChecker(0xbe4fc0, 0xc42680a000, 0xc42062e0c0, 0x0, 0x0, 0x0, 0xc420575080, 0x32)
	/go/src/boscoin.io/sebak/lib/common/checker.go:24 +0xe9
boscoin.io/sebak/lib.(*NodeRunner).handleMessage(0xc426850410)
	/go/src/boscoin.io/sebak/lib/node_runner.go:248 +0x4df
created by boscoin.io/sebak/lib.(*NodeRunner).Start
	/go/src/boscoin.io/sebak/lib/node_runner.go:76 +0x51
FAIL	boscoin.io/sebak/lib	40.646s
```

**Comment by kfangw** [comment]
```
=== RUN   TestNodeRunnerSerializedPayment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7f5768]

goroutine 53008 [running]:
boscoin.io/sebak/lib.(*VotingResult).LatestStaging(...)
	/go/src/boscoin.io/sebak/lib/voting.go:311
boscoin.io/sebak/lib.(*VotingResult).IsClosed(...)
	/go/src/boscoin.io/sebak/lib/voting.go:125
boscoin.io/sebak/lib.(*ISAAC).receiveBallotVotingStates(0xc4268ef400, 0xc454b32448, 0x6, 0xc44e9a8fc0, 0x2c, 0xc4269401e0, 0x58, 0xc454a80680, 0x38, 0xc44e9a8ff0, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:178 +0x238
boscoin.io/sebak/lib.(*ISAAC).ReceiveBallot(0xc4268ef400, 0xc454b32448, 0x6, 0xc44e9a8fc0, 0x2c, 0xc4269401e0, 0x58, 0xc454a80680, 0x38, 0xc44e9a8ff0, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:85 +0x145
boscoin.io/sebak/lib.CheckNodeRunnerHandleBallotReceiveBallot(0x9a2840, 0xc4268e6820, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/boscoin.io/sebak/lib/node_runner_checker.go:163 +0xec
boscoin.io/sebak/lib/common.RunChecker(0x9a2840, 0xc4268e6820, 0xc4204757c0, 0x0, 0x0, 0x0, 0xc458bcc580, 0x32)
	/go/src/boscoin.io/sebak/lib/common/checker.go:24 +0xe9
boscoin.io/sebak/lib.(*NodeRunner).handleMessage(0xc437dd4680)
	/go/src/boscoin.io/sebak/lib/node_runner.go:248 +0x497
created by boscoin.io/sebak/lib.(*NodeRunner).Start
	/go/src/boscoin.io/sebak/lib/node_runner.go:76 +0x51
FAIL	boscoin.io/sebak/lib	47.972s
```
https://circleci.com/gh/bosnet/sebak/719?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kfangw** [comment]
We almost solve the issue.

i think only one left issue is this.
https://github.com/bosnet/sebak/issues/147

**Comment by Geod24** [comment]
I think this has been long solved
