### ISSUE TITLE
nil pointer dereference in voting.go:311

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#144]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7f5768]

goroutine 53008 [running]:
boscoin.io/sebak/lib.(*VotingResult).LatestStaging(...)
	/go/src/boscoin.io/sebak/lib/voting.go:311
boscoin.io/sebak/lib.(*VotingResult).IsClosed(...)
	/go/src/boscoin.io/sebak/lib/voting.go:125
boscoin.io/sebak/lib.(*ISAAC).receiveBallotVotingStates(0xc4268ef400, 0xc454b32448, 0x6, 0xc44e9a8fc0, 0x2c, 0xc4269401e0, 0x58, 0xc454a80680, 0x38, 0xc44e9a8ff0, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:178 +0x238
boscoin.io/sebak/lib.(*ISAAC).ReceiveBallot(0xc4268ef400, 0xc454b32448, 0x6, 0xc44e9a8fc0, 0x2c, 0xc4269401e0, 0x58, 0xc454a80680, 0x38, 0xc44e9a8ff0, ...)
	/go/src/boscoin.io/sebak/lib/isaac.go:85 +0x145
boscoin.io/sebak/lib.CheckNodeRunnerHandleBallotReceiveBallot(0x9a2840, 0xc4268e6820, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/boscoin.io/sebak/lib/node_runner_checker.go:163 +0xec
boscoin.io/sebak/lib/common.RunChecker(0x9a2840, 0xc4268e6820, 0xc4204757c0, 0x0, 0x0, 0x0, 0xc458bcc580, 0x32)
	/go/src/boscoin.io/sebak/lib/common/checker.go:24 +0xe9
boscoin.io/sebak/lib.(*NodeRunner).handleMessage(0xc437dd4680)
	/go/src/boscoin.io/sebak/lib/node_runner.go:248 +0x497
created by boscoin.io/sebak/lib.(*NodeRunner).Start
	/go/src/boscoin.io/sebak/lib/node_runner.go:76 +0x51
FAIL	boscoin.io/sebak/lib	47.972s
```

**Comment by Charleslee522** [comment]
This is occured when running in circleci

**Comment by Charleslee522** [comment]
When I added `Lock()` and `defer Unlock()` in all methods in VotingResult, no error is occurred.
So I guess, The reason was a VotingResult that was unexpectedly deleted.
There are three solutions I think.
1. Null checking everywhere in `VotingResult` methods.
1. Locking in all `VotingResult` methods.
1. Using the copied `VotingResult` object, not pointer.
```
func **(vr VotingResult)** LatestStaging() VotingStateStaging {
	if len(vr.Staging) < 1 {
		return VotingStateStaging{}
	}
	return vr.Staging[len(vr.Staging)-1]
}
```
