### ISSUE TITLE
negative wait group error in `TestNodeRunnerSaveBlock`

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#303]
```
panic: sync: negative WaitGroup counter

goroutine 110449 [running]:
sync.(*WaitGroup).Add(0xc42c13e5c0, 0xffffffffffffffff)
	/usr/local/opt/go/libexec/src/sync/waitgroup.go:73 +0x133
sync.(*WaitGroup).Done(0xc42c13e5c0)
	/usr/local/opt/go/libexec/src/sync/waitgroup.go:98 +0x34
boscoin.io/sebak/lib.TestNodeRunnerSaveBlock.func1(0x4, 0x15edca0, 0xc4591d41a0, 0x15eed20, 0xc420495be0)
	/Users/charles/go/src/boscoin.io/sebak/lib/node_runner_test.go:281 +0x61
boscoin.io/sebak/lib/common.RunChecker(0x15edca0, 0xc4591d41a0, 0xc4202e0c50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/charles/go/src/boscoin.io/sebak/lib/common/checker.go:56 +0x153
boscoin.io/sebak/lib.(*NodeRunner).handleBallotMessage(0xc4200c9d40, 0x15861ac, 0x6, 0xc45f2f9200, 0x2be, 0x600, 0x0, 0x0)
	/Users/charles/go/src/boscoin.io/sebak/lib/node_runner.go:354 +0x508
boscoin.io/sebak/lib.(*NodeRunner).handleMessage(0xc4200c9d40)
	/Users/charles/go/src/boscoin.io/sebak/lib/node_runner.go:277 +0x544
created by boscoin.io/sebak/lib.(*NodeRunner).Start
	/Users/charles/go/src/boscoin.io/sebak/lib/node_runner.go:171 +0x94
```
@spikeekips Please check this bug :)

**Comment by spikeekips** [comment]
This will be help.
```diff
diff --git a/lib/node_runner_test.go b/lib/node_runner_test.go
index b222bf3..26eede8 100644
--- a/lib/node_runner_test.go
+++ b/lib/node_runner_test.go
@@ -272,7 +272,7 @@ func TestNodeRunnerSaveBlock(t *testing.T) {
        var wg sync.WaitGroup
        wg.Add(numberOfNodes)
        checkerDeferFunc := func(n int, checker sebakcommon.Checker, err error) {
-               if _, ok := err.(sebakcommon.CheckerStop); !ok {
+               if _, ok := err.(CheckerStopCloseConsensus); !ok {
                        return
                }
                wg.Done()
```

**Comment by spikeekips** [comment]
@Charleslee522 If you found this bug in https://github.com/bosnet/sebak/tree/new-proposer, I will patch.

**Comment by Charleslee522** [comment]
@spikeekips Exactly. I found it in new-proposer branch :)

**Comment by spikeekips** [comment]
I also found this error in my local machine, but it was rarely occurred. Anyway, to make this error often, I created new virtual machine and it has the limited resources, 1G CPU and 1G memory. I think it is similar with the circielci env.

Sometimes `TestNodeRunnerSaveBlock` was successfully done, but `panic: sync: negative WaitGroup counter` was found often. To make it clearer, I added log messages, it prints the `LocalNode.Alias()`, `Block.Height` when the consensus finished. In current impl, when consensus finishes, the new block always will be stacked up. I also patched to prevent `negative WaitGroup coutner` error.

```
node=A: GD7C.A7DL
node=B: GAYX.RP6V
node=C: GBXE.DBIQ
node=D: GCQ2.AOK3

1536200110705094962 consensus finished: node=A Ballot.H.ProposerSignature=4Uv4 block.Height=1
1536200112166705953 consensus finished: node=B Ballot.H.ProposerSignature=4Uv4 block.Height=1
1536200112649950756 consensus finished: node=C Ballot.H.ProposerSignature=4Uv4 block.Height=1

1536200131964723634 consensus finished: node=B Ballot.H.ProposerSignature=4Fcn block.Height=2
1536200133412641887 consensus finished: node=C Ballot.H.ProposerSignature=4Fcn block.Height=2
1536200133420341401 consensus finished: node=D Ballot.H.ProposerSignature=4Fcn block.Height=2
1536200133679536835 consensus finished: node=A Ballot.H.ProposerSignature=4Fcn block.Height=2

1536200146652778759 consensus finished: node=A Ballot.H.ProposerSignature=2mpg block.Height=3
1536200146682851126 consensus finished: node=D Ballot.H.ProposerSignature=2mpg block.Height=3
1536200146716537913 consensus finished: node=B Ballot.H.ProposerSignature=2mpg block.Height=3
1536200147043145384 consensus finished: node=C Ballot.H.ProposerSignature=2mpg block.Height=3
```

> I added these log messages in `lib/node_runner_test.go`.
```
277     checkerDeferFunc := func(n int, checker sebakcommon.Checker, err error) {
278         if _, ok := err.(CheckerStopCloseConsensus); !ok {
279             return
280         }
281
282         ballot := checker.(*BallotChecker).Ballot
283         node := checker.(*BallotChecker).LocalNode
284         thisBallotHash := ballot.H.ProposerSignature
285         fmt.Printf(
286             "%d consensus finished node=%s same=%v current=%s Ballot.H.ProposerSignature=%s block.Height=%d bloc    k.Hash=%s\n",
287             time.Now().UnixNano(),
288             node,
289             ballotHash == thisBallotHash,
290             ballotHash,
291             thisBallotHash,
292             ballot.B.Proposed.Round.BlockHeight,
293             ballot.B.Proposed.Round.BlockHash,
294         )
295         if ballotHash == "" {
296             ballotHash = thisBallotHash
297         } else if ballotHash != thisBallotHash {
298             return
299         }
300         wg.Done()
301     }
```

This is the filtered log messages. The problematic node is `D`. In `block.Height=1`, it failed to finish consensus for height 1. We can find the reason in the log.

```
t=2018-09-06T02:15:11+0000 lvl=dbug msg="round expired" module=sebak node=GCQ2.AOK3 stack=[boscoin.io/sebak/lib/node_runner.go:423]
t=2018-09-06T02:15:11+0000 lvl=dbug msg="calculated proposer" module=sebak node=GCQ2.AOK3 proposer=GCQ2QQGZFMLCWTM52BLOTACQOJJSOOPTA4EDLYLLOQN747XCAOK3RRPX block.Height=1 stack=[boscoin.io/sebak/lib/node_runner.go:434]
```

> The log message, 'round expired' part is I added. 

Node, `D` did expire the running round for `block.Height=1`. I guess the performance of this machine is so poor for running 4 node, especially these nodes were using `HTTP2Network`. Before `D` receives the `ACCEPT` ballots for block.Height=1, the other nodes finished consensus and moved to next proposer and `D` still remained in the previous block.Height=1.

---

As a conclusion, circleci env is not suitable for consensus testing with `NodeRunner`, including `integration_test`. We need to find another way to test them, I think the E2E testing env will be best place, not circleci. We can use circleci for basic unit testing.

**Comment by spikeekips** [comment]
Especially 'negative waitgroup' issue can be occurred in local env, this can be resolved like this.
```go
var finishedNodes []string
checkerDeferFunc := func(n int, checker sebakcommon.Checker, err error) {
	if _, ok := err.(sebakcommon.CheckerStop); !ok {
		return
	}

	node := checker.(*BallotChecker).LocalNode.Address()
	if _, found := sebakcommon.InStringArray(finishedNodes, node); found {
		return
	}
	finishedNodes = append(finishedNodes, node)
	wg.Done()
}
```

**Comment by spikeekips** [comment]
It was diminished, right?
