### ISSUE TITLE
'panic: test timed out after 8m0s' in `TestSubscribe`

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#808]
In CircielCI test, `TestSubscribe` failed too often with these messages,
```
=== RUN   TestSubscribe
coverage: 43.5% of statements
panic: test timed out after 8m0s

goroutine 143 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0x13a
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive, 7 minutes]:
testing.(*T).Run(0xc00021c000, 0xc612e8, 0xd, 0xc80438, 0xc000115b01)
	/usr/local/go/src/testing/testing.go:879 +0x689
testing.runTests.func1(0xc00021c000)
	/usr/local/go/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc00021c000, 0xc000115d20)
	/usr/local/go/src/testing/testing.go:827 +0x163
testing.runTests(0xc0001c4180, 0x1173f20, 0x10, 0x10, 0xc000115dc8)
	/usr/local/go/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc000210000, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x2ef
main.main()
	_testmain.go:142 +0x333

goroutine 156 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000752380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20180331014930-714f901b98fd/leveldb/util/buffer_pool.go:206 +0x1a6
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20180331014930-714f901b98fd/leveldb/util/buffer_pool.go:237 +0x2d0

...
FAIL	boscoin.io/sebak/lib/node/runner/api	480.027s
Exited with code 1
```
The entire test output can be found at https://gist.github.com/spikeekips/d23bd1fb604ed1d6531cb49f97e18826 .

**Comment by Charleslee522** [comment]
Is this critical or not??

**Comment by spikeekips** [comment]
This is critical only for testing, but it occurs too often.
